# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TestCocoapod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestCocoapod
    # pod 'MessageKit'  # Branch 3.0.0-swift5
    pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit.git', :branch => '3.0.0-swift5'


end
